services:
  # 1. Service Aplikasi (Laravel)
  app:
    build: .
    container_name: laravel_app
    restart: always
    env_file: .env
    networks:
      - laravel-net

  # 2. Service Web Server (Nginx)
  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80" 
    volumes:
      - ./:/var/www # Nginx butuh akses ke file public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app # Nginx jalan setelah App jalan
    networks:
      - laravel-net

  # 3. Service Database (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel} 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql # Agar data tidak hilang saat container dimatikan
    networks:
      - laravel-net


  node:
    image: node:18-alpine
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173" # Port default Vite
    command: npm run dev
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  dbdata:
    driver: local
